export const DECREMENT_MAIN_COUNTER = 'DECREMENT_MAIN_COUNTER'
export const INCREMENT_MAIN_COUNTER = 'INCREMENT_MAIN_COUNTER'

export const SET_CYCLE_TIME = 'SET_CYCLE_TIME'
export const SET_SHORT_BRAKE_TIME = 'SET_SHORT_BRAKE_TIME'
export const SET_LONG_BRAKE_TIME = 'SET_LONG_BRAKE_TIME'
